# update environment:
# conda env update --prefix ./condaenv --file environment.yml  --prune

channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pylint
  - pytest
  - regex
  - numpy
  - num2words
  - ipython
  - toolz
